ERROR -> 2023-11-13 17:01:00,147 -> log -> log.py -> Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `phone_number` is not valid for model `User`.
ERROR -> 2023-11-13 17:01:01,171 -> log -> log.py -> Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `phone_number` is not valid for model `User`.
ERROR -> 2023-11-13 17:29:08,131 -> log -> log.py -> Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/views.py", line 96, in get
    schema = generator.get_schema(request, self.public)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 38, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 129, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/openapi.py", line 685, in setdefault
    ret = maker()
          ^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 98, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nurdintaabaldyev/glovo_hackaathon/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `phone_number` is not valid for model `User`.
